apiVersion: v1
kind: Service
metadata:
  labels:
    app: beta
    component: service
  name: beta-canary
  namespace: foo
spec:
  ports:
  - name: grpc-port
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: beta
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
